### ISSUE TITLE
logo

### ISSUE THREAD

**Issue by jonschlinkert** [begin/artwork#1]
Logo guidelines.

## Details

- **organization name**: `begin`
- **description**: It's never too late to learn.

## Market

- designers and developers

## Messaging

**Primary concept**

Please attempt to convey these concepts in the logo:

- begin
- take action
- start now

**Secondary concepts**

 These concepts can serve as inspiration, but aren't as important to the messaging:

- learning
- getting started
- growth

## Design

- **style**: I'd like for the logo to be "iconic" and minimalist in style. 
- **color**: The logo does not need to be monochromatic, but it must contain an "organic" green somewhere in the logo. 

**Special notes**

Our logos will most commonly be displayed in the following locations:

- dropdown menus on GitHub
- as profile pictures
- project [readmes](https://github.com/assemble/assemble)
- blogs and social media

**Guidelines**

Please follow these guidelines to ensure the logo displays and scales well in those locations:

- no mascots or words, but single letters are okay
- the logo must display well on black, white and light gray backgrounds

**Comment by jonschlinkert** [comment]
## Examples

Below are links to some of our other projects that have logos that can serve as inspiration for the simplicity and minimalism that we'd like to see in our logo designs.
- https://github.com/base/base
- https://github.com/assemble/assemble
- https://github.com/generate/generate
- https://github.com/update/update
- https://github.com/verb/verb

**Logo examples**

![s-brand-icons-colored-001](https://cloud.githubusercontent.com/assets/383994/18454043/29c7acb4-7910-11e6-9898-e999965a7efa.jpg)

**Comment by tunnckoCore** [comment]
What's the purpose of @begin? Some (begginers) guides or?

**(link to base missing ;d)**

**Comment by jonschlinkert** [comment]
Yeah, I'm creating this issue for a purpose, so I'm going to delete the comments that don't relate to it, but we can create another issue

**Comment by jonschlinkert** [comment]
## Org profile example

See https://github.com/begin for the live page

---

<br>

![image](https://cloud.githubusercontent.com/assets/383994/18456035/dcd8060e-791b-11e6-842d-67751d718c62.png)

**Comment by jonschlinkert** [comment]
## Readme example

See https://github.com/assemble/assemble for the live page

---

<br>

![image](https://cloud.githubusercontent.com/assets/383994/18456056/fa72087c-791b-11e6-8f38-18ccfe551ec7.png)

**Comment by jonschlinkert** [comment]
## Dropdowns

### blue background

<br>
<br>

![image](https://cloud.githubusercontent.com/assets/383994/18456068/1658a5be-791c-11e6-9daf-30fc853ec27c.png)

<br>
<br>

***

<br>
<br>

### white background

<br>
<br>

![image](https://cloud.githubusercontent.com/assets/383994/18456089/3eefe780-791c-11e6-8440-8ad143ebfed2.png)

**Comment by jonschlinkert** [comment]
## Concepts

![c3579_begin_logo_01_mockup](https://cloud.githubusercontent.com/assets/383994/18618049/2b6631bc-7dac-11e6-85d5-17dd46972bf2.jpg)
![c3579_begin_logo_01](https://cloud.githubusercontent.com/assets/383994/18618050/2f4823c6-7dac-11e6-8a7e-295ff1d046af.png)
![c3579_begin_logo_02_mockup](https://cloud.githubusercontent.com/assets/383994/18618052/325bf470-7dac-11e6-8975-b60e90336dda.jpg)
![c3579_begin_logo_01 1](https://cloud.githubusercontent.com/assets/383994/18618055/439d1656-7dac-11e6-9d00-b3aa81560e62.png)

**Comment by jonschlinkert** [comment]
## Winner

We chose this logo.

---

![c3579_begin_logo_01 1](https://cloud.githubusercontent.com/assets/383994/18618060/52f9f63c-7dac-11e6-823b-8abe9f1ff1b5.png)

**Comment by cg-cnu** [comment]
Hey @jonschlinkert 
Sorry for bringing this issue from the dead! 
I saw this issue a while back and designed few logos but never managed to post them here. 

I really like the set of logos you have made for all the projects. They are following a theme in terms of the shape and patterns. Except for `begin`. Hope you understood what I mean. 

So, here is what I have designed for base to maintain the same theme across other repos.

<img width="556" alt="begin-1" src="https://user-images.githubusercontent.com/2767425/37171897-54ae6834-2335-11e8-833b-b768788550a5.png">

I finally settled on 3. Would like to hear your comments 😄

**Comment by jonschlinkert** [comment]
> Would like to hear your comments

They look great!

> I really like the set of logos you have made for all the projects. They are following a theme in terms of the shape and patterns. 

Thank you! 

> Except for begin. Hope you understood what I mean.

Yes, absolutely. good observation! We had considered making `begin` a part of [toolkit](https://github.com/node-toolkit/toolkit) but ultimately decided to keep it separate (we haven't even really "launched" toolkit yet, but that will happen soon!). For this reason, we decided to go with a different look.

**Comment by cg-cnu** [comment]
Completely make sense! Good luck on the launch! 👍
